name: FTP deploy on push
on: push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: sochinen.ftp.tools
        username: sochinen_testgit
        password: me4Di9V2E5
        server-dir: /home/sochinen/start-site.com.ua/first_rep
